name: Feature request
description: Suggest an idea for this project
labels: [enhancement]
title: "[Feature]: "
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an improvement!
  - type: input
    id: motivation
    attributes:
      label: Motivation
      description: What problem does this feature solve?
      placeholder: e.g., Users can't...
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Describe the solution you'd like
      placeholder: A clear and concise description
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Describe any alternative solutions you've considered
  - type: textarea
    id: details
    attributes:
      label: Additional context
      description: Add any other context, mockups, or screenshots
